## Contents

- Random forest classifier(more accuracy than any other algorithm) 
    - called as ensemble technique
    - Present in Ensemble classifier
    - Random forest - group of decision trees
    - We will consider the output of each decision tree and take the highest repeated values as our result
    


- If decision tree has overfitting(low bias, high variance) the use random forest 

In [1]:
import pandas as pd
import matplotlib.pyplot as plt

In [2]:
df = pd.read_csv("heart.csv")
df.head()

age  sex  cp  trestbps  chol  fbs  restecg  thalach  exang  oldpeak  slope  \
0   63    1   3       145   233    1        0      150      0      2.3      0   
1   37    1   2       130   250    0        1      187      0      3.5      0   
2   41    0   1       130   204    0        0      172      0      1.4      2   
3   56    1   1       120   236    0        1      178      0      0.8      2   
4   57    0   0       120   354    0        1      163      1      0.6      2   

   ca  thal  target  
0   0     1       1  
1   0     2       1  
2   0     2       1  
3   0     2       1  
4   0     2       1

In [3]:
x = df.drop("target",axis =1)
y = df["target"]

In [15]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(x,y,train_size=0.7,random_state=25)
from sklearn.ensemble import RandomForestClassifier
model = RandomForestClassifier()
model.fit(x_train,y_train)

RandomForestClassifier()

In [9]:
y_pred = model.predict(x_test)

In [10]:
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score
accuracy_score(y_test, y_pred)

0.8351648351648352

In [12]:
help(RandomForestClassifier())

Help on RandomForestClassifier in module sklearn.ensemble._forest object:

class RandomForestClassifier(ForestClassifier)
 |  RandomForestClassifier(n_estimators=100, *, criterion='gini', max_depth=None, min_samples_split=2, min_samples_leaf=1, min_weight_fraction_leaf=0.0, max_features='auto', max_leaf_nodes=None, min_impurity_decrease=0.0, min_impurity_split=None, bootstrap=True, oob_score=False, n_jobs=None, random_state=None, verbose=0, warm_start=False, class_weight=None, ccp_alpha=0.0, max_samples=None)
 |  
 |  A random forest classifier.
 |  
 |  A random forest is a meta estimator that fits a number of decision tree
 |  classifiers on various sub-samples of the dataset and uses averaging to
 |  improve the predictive accuracy and control over-fitting.
 |  The sub-sample size is controlled with the `max_samples` parameter if
 |  `bootstrap=True` (default), otherwise the whole dataset is used to build
 |  each tree.
 |  
 |  Read more in the :ref:`User Guide <forest>`.
 |  
 |  

In [13]:
import numpy as np
from sklearn.model_selection import RandomizedSearchCV
## n_estimators no of trees in random forest
n_estimators = [int(x) for x in np.linspace(start=200,stop=2000,num=10)]
## max_features is no of features at every split
max_features = ["auto","sqrt"]
##max_depth
max_depth = [int(x) for x in np.linspace(100,500,num=11)]

random_grid = {"n_estimators":n_estimators, "max_features":max_features,"max_depth":max_depth}
rfc = RandomizedSearchCV(estimator = model,param_distributions = random_grid,n_iter=100,cv=3,random_state=42,verbose=2,n_jobs=-1)
rfc.fit(x_train,y_train)
print(rfc.best)

Fitting 3 folds for each of 100 candidates, totalling 300 fits
{'n_estimators': 400, 'max_features': 'auto', 'max_depth': 180}


In [16]:
model = RandomForestClassifier(n_estimators=400, max_features= 'auto', max_depth= 180)
model.fit(x_train,y_train)

RandomForestClassifier(max_depth=180, n_estimators=400)

In [17]:
from sklearn.model_selection import cross_val_score
from sklearn.metrics import accuracy_score, confusion_matrix,precision_score
y_pred = model.predict(x_test)
cv_score = cross_val_score(model,x,y,cv=10)
print(accuracy_score(y_test, y_pred))

0.8461538461538461


In [18]:
confusion_matrix(y_pred,y_test)

array([[32,  6],
       [ 8, 45]], dtype=int64)

In [20]:
cv_score

array([0.87096774, 0.83870968, 0.87096774, 0.9       , 0.86666667,
       0.8       , 0.76666667, 0.83333333, 0.73333333, 0.8       ])

In [21]:
cv_score.mean()

0.8280645161290323

## RandomForestRegressor

In [22]:
df1 = pd.read_csv("age_salary_hours.csv")
df1

Age  Annual Salary  Weekly hours                    Education
0     72       160000.0          40.0  Bachelor's degree or higher
1     72       100000.0          50.0  Bachelor's degree or higher
2     31       120000.0          40.0  Bachelor's degree or higher
3     28        45000.0          40.0  Bachelor's degree or higher
4     54        85000.0          40.0  Bachelor's degree or higher
..   ...            ...           ...                          ...
495   27        47000.0          40.0  Bachelor's degree or higher
496   53       132000.0          70.0  Bachelor's degree or higher
497   51        10100.0          20.0  Bachelor's degree or higher
498   32        57000.0          35.0  Bachelor's degree or higher
499   18        18700.0          20.0  Attended college, no degree

[500 rows x 4 columns]

In [25]:
x = df1["Weekly hours"].values.reshape(-1,1)
x

array([[40.],
       [50.],
       [40.],
       [40.],
       [40.],
       [40.],
       [ 0.],
       [40.],
       [ 0.],
       [50.],
       [50.],
       [ 0.],
       [ 0.],
       [40.],
       [45.],
       [27.],
       [40.],
       [ 0.],
       [55.],
       [50.],
       [40.],
       [40.],
       [40.],
       [45.],
       [40.],
       [40.],
       [ 0.],
       [36.],
       [40.],
       [40.],
       [29.],
       [40.],
       [35.],
       [ 0.],
       [ 0.],
       [40.],
       [40.],
       [30.],
       [35.],
       [ 0.],
       [50.],
       [13.],
       [40.],
       [40.],
       [ 0.],
       [ 0.],
       [40.],
       [43.],
       [40.],
       [60.],
       [ 0.],
       [ 0.],
       [20.],
       [35.],
       [30.],
       [45.],
       [10.],
       [ 0.],
       [40.],
       [50.],
       [50.],
       [ 0.],
       [ 0.],
       [ 0.],
       [39.],
       [50.],
       [40.],
       [ 0.],
       [45.],
       [ 0.],
       [ 0.],
      

In [27]:
y = df1["Annual Salary"].values.reshape(-1,1)

In [28]:
from sklearn.ensemble import RandomForestRegressor
model = RandomForestRegressor()
model.fit(x,y)

<ipython-input-28-c0fb4e276968>:3: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  model.fit(x,y)


RandomForestRegressor()

In [29]:
y_pred = model.predict(x)

In [31]:
model.score(y,y_pred)*100

-48.5027792389767